INSERT INTO ALBUM (TITLE, ARTIST, RELEASEYEAR, GENRE) VALUES
    ('Nirvana', 'Nevermind', '1991', 'Rock'),
    ('The Beach Boys', 'Pet Sounds', '1966', 'Rock'),
    ('Marvin Gaye', 'What''s Going On', '1971', 'Rock'),
    ('Jimi Hendrix Experience', 'Are You Experienced?', '1967', 'Rock'),
    ('U2', 'The Joshua Tree', '1987', 'Rock'),
    ('The Beatles', 'Abbey Road', '1969', 'Rock'),
    ('Fleetwood Mac', 'Rumours', '1977', 'Rock'),
    ('Elvis Presley', 'Sun Sessions', '1976', 'Rock'),
    ('Michael Jackson', 'Thriller', '1982', 'Pop'),
    ('The Rolling Stones', 'Exile on Main Street', '1972', 'Rock'),
    ('Bruce Springsteen', 'Born to Run', '1975', 'Rock'),
    ('The Clash', 'London Calling', '1980', 'Rock'),
    ('The Eagles', 'Hotel California', '1976', 'Rock'),
    ('Led Zeppelin', 'Led Zeppelin', '1969', 'Rock'),
    ('Led Zeppelin', 'IV', '1971', 'Rock'),
    ('Police', 'Synchronicity', '1983', 'Rock'),
    ('U2', 'Achtung Baby', '1991', 'Rock'),
    ('The Rolling Stones', 'Let it Bleed', '1969', 'Rock'),
    ('The Beatles', 'Rubber Soul', '1965', 'Rock'),
    ('The Ramones', 'The Ramones', '1976', 'Rock'),
    ('Queen', 'A Night At The Opera', '1975', 'Rock'),
    ('Boston', 'Don''t Look Back', '1978', 'Rock'),
    ('BB King', 'Singin'' The Blues', '1956', 'Blues'),
    ('Albert King', 'Born Under A Bad Sign', '1967', 'Blues'),
    ('Muddy Waters', 'Folk Singer', '1964', 'Blues'),
    ('The Fabulous Thunderbirds', 'Rock With Me', '1979', 'Blues'),
    ('Robert Johnson', 'King of the Delta Blues', '1961', 'Blues'),
    ('Stevie Ray Vaughan', 'Texas Flood', '1983', 'Blues'),
    ('Stevie Ray Vaughan', 'Couldn''t Stand The Weather', '1984', 'Blues');
